import os
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
# This points directly to your exact function and Student DTO data structure
from lesson_recap_pipeline import generate_structured_recap, Student, get_db

from pydantic import BaseModel, EmailStr, Field
from datetime import date
from typing import Optional

# ==========================================
# 👥 STUDENT DATA VALIDATION SCHEMAS
# ==========================================

class StudentBase(BaseModel):
    """Core student attributes checked on both input and output."""
    name: str = Field(..., min_length=1, max_length=100, description="Student's full name.")
    email: EmailStr = Field(..., description="A validated, properly formatted email address.")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age must be a realistic positive integer.")

class StudentCreate(StudentBase):
    """Schema for validating data when adding a brand new student."""
    pass

class StudentResponse(StudentBase):
    """Schema for structuring data sent back to the frontend dashboard."""
    id: int = Field(..., description="The unique database primary key.")

    class Config:
        from_attributes = True


# ==========================================
# 🎵 LESSON RECAP DATA VALIDATION SCHEMAS
# ==========================================

class LessonRecapBase(BaseModel):
    """Core fields of a parsed AI lesson summary session."""
    student_id: int = Field(..., description="The database ID of the student this lesson belongs to.")
    lesson_date: date = Field(default_factory=date.today, description="The date of the lesson.")
    
    # Core technical blocks generated by your transcription engine
    summary_overview: str = Field(..., min_length=10, description="Broad summary of what was covered.")
    theory_covered: Optional[str] = Field(None, description="Scales, chords, or music theory concepts taught.")
    technique_exercises: Optional[str] = Field(None, description="Technical drills, fingerings, or warm-ups assigned.")
    homework_assignments: str = Field(..., min_length=5, description="Explicit practice expectations for the week.")

class LessonRecapCreate(LessonRecapBase):
    """Schema for validating data when saving a brand-new parsed recap."""
    pass

class LessonRecapResponse(LessonRecapBase):
    """Schema for returning lesson details to your frontend UI."""
    id: int = Field(..., description="Unique primary key for the lesson record.")

    class Config:
        from_attributes = True

app = FastAPI(title="Ageless Tune Studio Pipeline Bridge")

# Security Gateway for Lovable cross-origin requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class LessonRequest(BaseModel):
    student_name: str
    raw_notes: str

@app.post("/api/recap", response_model=LessonRecapResponse, status_code=201)
async def process_lesson_recap(payload: LessonRecapCreate, db: Session = Depends(get_db)):
    if not os.getenv("OPENAI_API_KEY"):
        raise HTTPException(status_code=500, detail="Missing OpenAI API Key on your local system environment.")
        
    try:
        # 1. Mock/Fetch student verification sequence 
        # (Using ID from the validated Pydantic payload)
        active_student = Student(
            id=payload.student_id,
            name="Studio Student",  
            age=12,
            gender="unknown",
            email="client@agelesstune.local"
        )
        
        # 2. Fire your orchestration engine using the clean, validated payload fields
        formatted_recap = generate_structured_recap(
            student=active_student,
            raw_transcript=payload.summary_overview, # Maps incoming text to pipeline processing
            persist=True # Keeps your SQLAlchemy SQLite commits perfectly intact
        )
        
        # 3. Return the fully structured validation data structure back to your frontend dashboard
        return LessonRecapResponse(
            id=99, # Placeholder primary key for this execution pass
            student_id=payload.student_id,
            lesson_date=payload.lesson_date,
            summary_overview=formatted_recap.get("summary_overview", payload.summary_overview),
            theory_covered=formatted_recap.get("theory_covered", payload.theory_covered),
            technique_exercises=formatted_recap.get("technique_exercises", payload.technique_exercises),
            homework_assignments=formatted_recap.get("homework_assignments", payload.homework_assignments)
        )
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))